repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b # v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
        exclude: ^input/[0-9]{4}/(?:example/)?day[0-9]{1,2}.txt$
    -   id: end-of-file-fixer
        exclude: ^input/[0-9]{4}/(?:example/)?day[0-9]{1,2}.txt$
    -   id: check-toml
-   repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a89e69d5772bdee97db1a6a898467b686e # 1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
        args: ["--all-features"]
    -   id: clippy
        args: ["--all-features", "--", "--deny", "warnings"]
-   repo: https://github.com/SuperTux88/adventofcode
    rev: 60a99126a98db97bb1b3ce3becad488456969e48 # current version
    hooks:
    -   id: create-day-tiles
        # only run when a new input file gets added, which means a new day was added
        files: ^input/[0-9]{4}/day[0-9]{1,2}.txt$
        args: ["rust"]
