repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
        exclude: ^input/[0-9]{4}/(?:example/)?day[0-9]{1,2}.txt$
    -   id: end-of-file-fixer
        exclude: ^input/[0-9]{4}/(?:example/)?day[0-9]{1,2}.txt$
    -   id: check-toml
-   repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a89e69d5772bdee97db1a6a898467b686e # 1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
        args: ["--all-features"]
    -   id: clippy
        args: ["--all-features", "--", "--deny", "warnings"]
-   repo: https://github.com/SuperTux88/adventofcode
    rev: be47fef7ad6593dba87e12fa5b617d9ebe133008 # current version
    hooks:
    -   id: create-day-tiles
        # only run when a new input file gets added, which means a new day was added
        files: ^input/[0-9]{4}/day[0-9]{1,2}.txt$
        args: ["rust"]
