# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "test"

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--all-features"]
extraneous_args = false
need_stdout = false

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets", "--all-features"]
extraneous_args = false
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--", "--color", "always", "run"]
need_stdout = true
allow_warnings = true

[jobs.run-release]
command = ["cargo", "run", "--release", "--", "--color", "always", "run"]
need_stdout = true
allow_warnings = true

[jobs.bench]
command = ["cargo", "run", "--", "--color", "always", "bench"]
need_stdout = true
allow_warnings = true

[jobs.bench-release]
command = ["cargo", "run", "--release", "--", "--color", "always", "bench"]
need_stdout = true
allow_warnings = true

[jobs.test]
command = ["./.bacon-wrapper.sh", "test"]
need_stdout = true
allow_warnings = true

[jobs.criterion]
command = ["./.bacon-wrapper.sh", "criterion"]
need_stdout = true
allow_warnings = true

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal global prefs.toml file instead.
[keybindings]

# jobs
d = "job:default"

a = "job:check-all"
c = "job:clippy-all"

shift-r = "job:run-release"

alt-b = "job:bench"
alt-shift-b = "job:bench-release"

alt-c = "job:criterion"

# toggles
s = "toggle-summary"
w = "toggle-wrap"
b = "toggle-backtrace"
