[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
colored = "2.0.0"
dirs = "4.0.0"
reqwest = { version = "0.11.13", default-features = false, features = ["blocking", "gzip", "rustls-tls"] }
